vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        service_image:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
